-- Custom Roles Seed for DeepSkills
-- Populates standard staff roles with granular module permissions

INSERT INTO custom_roles (name, description, icon, color, permissions, is_builtin, created_at, updated_at)
VALUES
  (
    'Admission Counsellor',
    'Manages prospective inquiries, lead follow-ups, courses, and student admissions.',
    '📞',
    'amber',
    '{
      "dashboard": "view",
      "counsellor": "full",
      "students": "view",
      "teachers": "none",
      "courses": "view",
      "attendance": "none",
      "tasks": "none",
      "results": "none",
      "finance": "none",
      "complaints": "none",
      "announcements": "view",
      "blog": "none",
      "referral": "full",
      "reports": "none",
      "hr": "none",
      "users": "none",
      "settings": "none"
    }'::jsonb,
    false,
    NOW(),
    NOW()
  ),
  (
    'Finance Officer',
    'Oversees fee collections, vouchers, installment records, and financial revenue reports.',
    '💼',
    'green',
    '{
      "dashboard": "view",
      "counsellor": "none",
      "students": "view",
      "teachers": "none",
      "courses": "view",
      "attendance": "none",
      "tasks": "none",
      "results": "none",
      "finance": "full",
      "complaints": "none",
      "announcements": "none",
      "blog": "none",
      "referral": "none",
      "reports": "full",
      "hr": "none",
      "users": "none",
      "settings": "none"
    }'::jsonb,
    false,
    NOW(),
    NOW()
  ),
  (
    'Academic Coordinator',
    'Coordinates daily academic operations, batch schedules, attendance, assignments, and exam results.',
    '📋',
    'blue',
    '{
      "dashboard": "view",
      "counsellor": "none",
      "students": "full",
      "teachers": "view",
      "courses": "full",
      "attendance": "full",
      "tasks": "full",
      "results": "full",
      "finance": "none",
      "complaints": "full",
      "announcements": "full",
      "blog": "none",
      "referral": "none",
      "reports": "view",
      "hr": "none",
      "users": "none",
      "settings": "none"
    }'::jsonb,
    false,
    NOW(),
    NOW()
  ),
  (
    'HR & Faculty Manager',
    'Manages faculty recruitment, job descriptions, contracts, onboarding, and leave requests.',
    '👔',
    'purple',
    '{
      "dashboard": "view",
      "counsellor": "none",
      "students": "none",
      "teachers": "full",
      "courses": "none",
      "attendance": "view",
      "tasks": "none",
      "results": "none",
      "finance": "none",
      "complaints": "view",
      "announcements": "none",
      "blog": "none",
      "referral": "none",
      "reports": "view",
      "hr": "full",
      "users": "none",
      "settings": "none"
    }'::jsonb,
    false,
    NOW(),
    NOW()
  ),
  (
    'Marketing & Media Specialist',
    'Publishes blog articles, site announcements, student testimonials, and referral campaigns.',
    '👤',
    'pink',
    '{
      "dashboard": "view",
      "counsellor": "none",
      "students": "none",
      "teachers": "none",
      "courses": "view",
      "attendance": "none",
      "tasks": "none",
      "results": "none",
      "finance": "none",
      "complaints": "none",
      "announcements": "full",
      "blog": "full",
      "referral": "full",
      "reports": "none",
      "hr": "none",
      "users": "none",
      "settings": "none"
    }'::jsonb,
    false,
    NOW(),
    NOW()
  ),
  (
    'Auditor / Executive Viewer',
    'Read-only administrative oversight across academic, financial, and operational reports.',
    '🔐',
    'gray',
    '{
      "dashboard": "full",
      "counsellor": "view",
      "students": "view",
      "teachers": "view",
      "courses": "view",
      "attendance": "view",
      "tasks": "view",
      "results": "view",
      "finance": "view",
      "complaints": "view",
      "announcements": "view",
      "blog": "view",
      "referral": "view",
      "reports": "full",
      "hr": "view",
      "users": "none",
      "settings": "none"
    }'::jsonb,
    false,
    NOW(),
    NOW()
  )
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color,
  permissions = EXCLUDED.permissions,
  updated_at = NOW();
